[package]
name = "findex"
version = "0.5.0"
edition = "2021"
authors = ["MD Gaziur Rahman Noor <mdgaziurrahmannoor@gmail.com>"]
description = "Highly customizable application finder with high performance. Written in Rust and uses GTK"
homepage = "https://github.com/mdgaziur/findex"
repository = "https://github.com/mdgaziur/findex"
license = "GPL3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = true

[profile.release]
incremental = true
lto = true

[dependencies]
gtk = { version = "0.14.3", features=["v3_22"] }
freedesktop_entry_parser = "1.2.0"
regex = "1"
shlex = "1.1.0"
nix = "0.23"
shellexpand = "2.1.0"
fuse-rust = "0.3.0"
toml = "0.5.8"
lazy_static = "1.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
